debug: true 
server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:   
  datasource: 
    url: jdbc:postgresql://localhost:5432/warehouse
    username: warehouseUser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true

logging:
  file:
    name: log/warehouse.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': warn
    '[org.hibernate]': info
    '[com.depo]': debug
    '[org.springframework.boot.autoconfigure]': error
    root: off

management: #actuator
  endpoints:   
    web:
      exposure:
        include: '*'
                  
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

depo:
  app:
    jwtSecret: warehouse@!123
    jwtExpirationMs: 86400000

info:
  application:
    name: 'Warehouse Backend App'
    description: 'This is a warehouse application'
    version: '@project.version@'
  
      


  
   
